// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqUa7j1dMZO_XNx_45-fWC5JCl4UH4pR0',
    appId: '1:370873476668:web:156645a20a4b8008c08539',
    messagingSenderId: '370873476668',
    projectId: 'cs361-final-project-1c6cf',
    authDomain: 'cs361-final-project-1c6cf.firebaseapp.com',
    storageBucket: 'cs361-final-project-1c6cf.appspot.com',
    measurementId: 'G-THC25XPJL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIZEMpZ_qDql7iUveigIr6d7UbIj5c_B4',
    appId: '1:370873476668:android:091e6681fd20e416c08539',
    messagingSenderId: '370873476668',
    projectId: 'cs361-final-project-1c6cf',
    storageBucket: 'cs361-final-project-1c6cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcBcCGrGhBKhoOdh05voXmdqJb1lWCXnk',
    appId: '1:370873476668:ios:3e7b6bce0012be01c08539',
    messagingSenderId: '370873476668',
    projectId: 'cs361-final-project-1c6cf',
    storageBucket: 'cs361-final-project-1c6cf.appspot.com',
    iosClientId: '370873476668-231gveaencqb6nhs785cbehd21r4r5kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssessmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcBcCGrGhBKhoOdh05voXmdqJb1lWCXnk',
    appId: '1:370873476668:ios:3e7b6bce0012be01c08539',
    messagingSenderId: '370873476668',
    projectId: 'cs361-final-project-1c6cf',
    storageBucket: 'cs361-final-project-1c6cf.appspot.com',
    iosClientId: '370873476668-231gveaencqb6nhs785cbehd21r4r5kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.classAssessmentApp',
  );
}
